apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-mock.fullname" . }}
  labels:
    {{- include "go-mock.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ .Values.mockConfig | nindent 4 }}
